package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.44

import (
	"context"
	"strconv"
	"tutorials/gqlgen-users/databaseConnector"
	"tutorials/gqlgen-users/graph/model"
)

// SaveCustomer is the resolver for the saveCustomer field.
func (r *mutationResolver) SaveCustomer(ctx context.Context, input model.NewCustomer) (bool, error) {
	customer := &model.Customer{
		CustomerID: input.CustomerID,
		Email:      input.ZipCode,
	}
	r.customer = append(r.customer, customer)
	return true, nil
}

// GetCustomer is the resolver for the getCustomer field.
func (r *queryResolver) GetCustomer(ctx context.Context, customerID string) (*model.Customer, error) {
	cid, _ := strconv.Atoi(customerID)
	var customer *databaseConnector.User
	var err error
	customer, err = databaseConnector.GetUserByID(uint(cid))

	if err != nil {
		// handle error
		return nil, err
	}

	// get the underlying byte slice.
	jsonbText, _ := customer.MetaData.Value()
	// Convert byte slice to string
	jsonString := string(jsonbText.([]byte))

	// map returned customer structure from the DB into the model
	c := model.Customer{
		CustomerID: strconv.FormatUint(uint64(customer.ID), 10),
		Username:   customer.Username,
		Email:      customer.Email,
		Age:        customer.Age,
		MetaData:   jsonString,
	}

	return &c, nil
}

// GetCustomerByMetaData is the resolver for the getCustomerByMetaData field.
func (r *queryResolver) GetCustomerByMetaData(ctx context.Context, metaData string) (*model.Customer, error) {
	customer, err := databaseConnector.GetUserByMetaData(metaData)

	if err != nil {
		// handle error
		return nil, err
	}

	// get the underlying byte slice.
	jsonbText, _ := customer.MetaData.Value()
	// Convert byte slice to string
	jsonString := string(jsonbText.([]byte))

	// map returned customer structure from the DB into the model
	c := model.Customer{
		CustomerID: strconv.FormatUint(uint64(customer.ID), 10),
		Username:   customer.Username,
		Email:      customer.Email,
		Age:        customer.Age,
		MetaData:   jsonString,
	}

	return &c, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
