// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Customer struct {
	CustomerID string `json:"customerId"`
	ZipCode    string `json:"zipCode"`
}

type Mutation struct {
}

type NewCustomer struct {
	CustomerID string `json:"customerId"`
	ZipCode    string `json:"zipCode"`
}

type Query struct {
}
